I cut and pasted the wrong URL. The correct file that I uploaded is under the "schoda01" branch...
Here is the correct link is https://github.com/schoda01/ProgrammingAssignment2/tree/schoda01
Sorry for making you take extra steps.
